- name: Dashboards
  icon: cogs
  url: /docs/README
  authority: ROLE_ADMIN
  children:
    - name: 'Projects'
      url: '/data/cms/sites'
      icon: 'globe'
      authority: ROLE_ADMIN
    - name: 'Content Types'
      url: '/data/cms/content-types'
      icon: 'cogs'
      authority: ROLE_ADMIN
    - name: 'Fields'
      url: '/data/cms/fields'
      icon: 'location-arrow'
      authority: ROLE_ADMIN
