# Menu Tree on Top Naviation
- name: CMS
  icon: book
  url: /docs/cms
  children:
    - name: Content Types
      url: /data/cms/content-types
      icon: question
    - name: Contents
      url: /data/cms/contents
      icon: question
