# Menu Tree on Top Naviation
- name: User Guide
  icon: question-circle
  url: /docs/user-guide
  children:
    - name: Deployments
      url: /docs/deployment
      sidebarUrl: 'assets/config/sidebar.yml'
      icon: paper-plane
    - name: Development
      url: /docs/development
      icon: boxes
